// jest.setup.ts - Mock @nestjs/swagger decorators to avoid ESM issues in tests
jest.mock('@nestjs/swagger', () => ({
  ApiTags: () => () => {},
  ApiBearerAuth: () => () => {},
  ApiOperation: () => () => {},
  ApiResponse: () => () => {},
  ApiParam: () => () => {},
  ApiProperty: () => () => {},
  ApiPropertyOptional: () => () => {},
  ApiExtraModels: () => () => {},
  getSchemaPath: jest.fn(),
  ApiQuery: () => () => {},
  ApiBody: () => () => {},
  ApiConsumes: () => () => {},
  ApiProduces: () => () => {},
  ApiHeader: () => () => {},
  ApiHeaders: () => () => {},
  ApiExcludeEndpoint: () => () => {},
  ApiExcludeController: () => () => {},
  ApiExtension: () => () => {},
  ApiDeprecated: () => () => {},
  ApiSecurity: () => () => {},
  ApiOkResponse: () => () => {},
  ApiCreatedResponse: () => () => {},
  ApiBadRequestResponse: () => () => {},
  ApiUnauthorizedResponse: () => () => {},
  ApiForbiddenResponse: () => () => {},
  ApiNotFoundResponse: () => () => {},
  ApiInternalServerErrorResponse: () => () => {},
  ApiDefaultResponse: () => () => {},
  ApiConflictResponse: () => () => {},
  ApiGoneResponse: () => () => {},
  ApiPreconditionFailedResponse: () => () => {},
  ApiPayloadTooLargeResponse: () => () => {},
  ApiUnsupportedMediaTypeResponse: () => () => {},
  ApiTooManyRequestsResponse: () => () => {},
  ApiUnprocessableEntityResponse: () => () => {},
}));